### ISSUE TITLE
Dark Theme items appear in white

### ISSUE THREAD

**Issue by arijitlaik** [edasubert/beamerMaterialDesign#2]
![screenshot_2018-05-30_06-24-26](https://user-images.githubusercontent.com/10157121/40692927-34e53644-63d2-11e8-9d6c-06be91443a40.png)

**Comment by edasubert** [comment]
Thank you for submitting an issue 🙂
Could you also provide the latex code so I can replicate it myself?

**Comment by arijitlaik** [comment]
for the sake of quick replication:
[https://www.overleaf.com/16550042zbpwkdprnbby](https://www.overleaf.com/16550042zbpwkdprnbby)

this is just recreated by using the dark theme option
```
\documentclass[aspectratio=43]{beamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\title{Material Design theme \\manual}
\date{\today}
\author[Šubert]{Eduard Šubert}

\usetheme{material}

\useDarkTheme
\usePrimary{4527A0}{311B92}{FFFFFF}
\useAccent{C6FF00}{000000}
```

**Comment by edasubert** [comment]
the issue was with mismatched color settings and card background settings, it is fixed now, give it a try :-)
