### ISSUE TITLE
how to position two figures in a row next to each other? 

### ISSUE THREAD

**Issue by alexlib** [edasubert/beamerMaterialDesign#3]
how to position two figures in a row next to each other? 

thanks in advance

**Comment by alexlib** [comment]
Found some workaround:
\begin{card}
\centering\includegraphics[width=.49\textwidth]{img1.jpg} \includegraphics[width=.49\textwidth]{img2.jpg}
\end{card}

**Comment by edasubert** [comment]
I would use columns and two cardImg like this:
```
\begin{frame}
\begin{multicols}{2}
[
\begin{cardTiny}
Two images side by side with columns.
\end{cardTiny}
]
\centering
\cardImg{img/rudolfinum.jpg}{0.48\textwidth}

\cardImg{img/rudolfinum.jpg}{0.48\textwidth}
\end{multicols}
\end{frame}
```
I added this to the example document so you can see for yourself

**Comment by alexlib** [comment]
Thanks. i think also worth mentioning `\usepackage{multicol}`
https://github.com/edasubert/beamerMaterialDesign/blob/fdb5853ad6640f5258033a26f5e5692c9295b727/materialDesignExample.tex#L3
